### ISSUE TITLE
"No Photoshop version detected."

### ISSUE THREAD

**Issue by derrickb** [JavierAroche/brackets-to-photoshop#1]
I get this message whenever I try to use the extension.

I got this on both Windows 7 x64 and Windows 10 x64.

In both cases I had Adobe Photoshop CC 2015 installed to the default directory:
C:\Program Files\Adobe\Adobe Photoshop CC 2015

**Comment by JavierAroche** [comment]
@derrickb, this extension is using Photoshop's AppleScript API to execute, therefore it only works for MacOS users unfortunately. I haven't found a similar API for Windows, but I will keep looking.

I added this little info to the README so it's not confusing. Thanks!

e8f13e258a6710fec8e5328804cbadaa04271047
