### ISSUE TITLE
Photoshop CC 2017

### ISSUE THREAD

**Issue by JavierAroche** [JavierAroche/brackets-to-photoshop#3]
Opening an issue for @DivineFrancis comment on commit 

https://github.com/JavierAroche/brackets-to-photoshop/commit/ffc98f8015e7614bdca89e77a43c885ce13c9969#commitcomment-20481820

> Salut quelqu'un pourrait m'aider à exécuter l’extension pour bracket à photoshop cc Version 2017

@DivineFrancis, are you using the extension on macOS?

**Comment by JavierAroche** [comment]
@DivineFrancis is currently using Windows, which is not currently supported. I'm still working on a release that will support Windows.

**Comment by keadith** [comment]
[node-error 8:47:41 AM] Br-Ps: 78:301: execution error: Erreur dans
Adobe Photoshop CC 2017 : Une erreur générale de Photoshop s'est
produite. Cette fonction n'est peut-être pas disponible dans cette
version de Photoshop.
- Erreur 61: Jeton non fermé.
Ligne: 158

J'utilise MacBook Pro retina now . Merci de vouloir m'aider frère


2017-01-18 20:04 GMT+01:00 Javier Aroche <notifications@github.com>:

**Comment by JavierAroche** [comment]
@DivineFrancis, it looks like the error is on your code (Line 158), not on the plugin itself.

**Comment by keadith** [comment]
Donc dans ce cas que pourais-je faire ?
Merci de m'avoir aider

2017-03-29 16:36 GMT+01:00 Javier Aroche <notifications@github.com>:
