### ISSUE TITLE
Seems to not be working with latest version (2018) of photoshop

### ISSUE THREAD

**Issue by dedoubleyou1** [JavierAroche/brackets-to-photoshop#5]
I get the following error in the Brackets console when running after updating photoshop:
`[node-error 2:36:42 PM] Br-Ps: 81:91: syntax error: Expected end of line but found identifier. (-2741)`

**Comment by januswow** [comment]
@dedoubleyou1
You can modify the extension information to work with PS CC 2018.
Open file "/Users/yourusername/Library/Application Support/Brackets/extensions/user/brackets-to-photoshop/lib/AdobeVersions.json", and add "photoshop-120" : "Adobe Photoshop CC 2018" to  photoshop block. Done!

**Comment by JavierAroche** [comment]
Thanks @januswow! That's right, any new versions can be added that way. I made a new release v0.0.6, so this should fix it.

Sorry for the delay on this guys. I'm not using Brackets as much these days, so it's hard to maintain this repo.
